# Generated by Django 5.2.4 on 2025-08-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['estado', 'pais'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50, verbose_name='Nombre')),
                ('iso', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_empresa', models.CharField(max_length=50, verbose_name='Tipo de empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de empresa',
                'verbose_name_plural': 'Tipos de empresa',
                'db_table': 'tipo_empresa',
                'ordering': ['tipo_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['ciudad', 'estado'],
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.pais', verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=12, verbose_name='Nº de Cédula')),
                ('numero_fiscal', models.CharField(max_length=10, verbose_name='RIF')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono(s)')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
